title:             Aezlo Blog
email:             aezloman@athelo.net
description:       The aezlo 🚀 blog
author:            Start Bootstrap
baseurl:           "/blog"
url:               "http://athelo.net"

# Social Profiles
twitter_username:  aezloman
github_username:   aezloX
facebook_username: #

# Build settings
markdown:          kramdown
paginate:          20
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
