title:             Aezlo Blog
email:             aezloman@athelo.net
description:       The aezlo 🚀 blog
author:            Start Bootstrap
baseurl:           "/blog"
url:               "http://athelo.net"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
